### ISSUE TITLE
could not build

### ISSUE THREAD

**Issue by zzuzhp** [AgoraIO-Community/Agora-Unreal-SDK#5]
im using unreal editor 4.26.2, i could not compile the example following README.
error reports:
[https://imgtu.com/i/Wdxylj](url)
[https://imgtu.com/i/WdxDfg](url)

and my dir structure looks like this:

[https://imgtu.com/i/WdxcXn](url)
[https://imgtu.com/i/Wdx66s](url)
[https://imgtu.com/i/WdxspQ](url)

what am i missing ? please help, thank you.

**Comment by zhangtao1104** [comment]
Do you confirm you had input your appId and download the plugin as README?

**Comment by zzuzhp** [comment]
> Do you confirm you had input your appId and download the plugin as README?

absolutely, step by step!
i downloaded the Agora_Unreal_FULL_SDK.zip(256MB (268908474 bytes)) from the link provided in the README, but after i the unzip the SDK, i found the dir structure (AgoraPlugin)is different from the one in the README picture. (for example, there is no Binaries dir in the sdk but your picture show it has, is it a generated one ?)

**Comment by HugoChaan** [comment]
This problem may be caused by the differennce on UE verion. May you try to use an alternative way to open the project? Open Unreal Engine first and load the project in it. The editor will notify you to convert to project into the adapted one. Just follow the instruction of the editor and you could open the project without any error occurred.

**Comment by zzuzhp** [comment]
this helps, thank you!
